#!/usr/bin/env python
# -*- coding: utf-8 -*-

import json
from celerymethods.utils import get_running_tasks

status, tasks = get_running_tasks('127.0.0.1')
print json.dumps(tasks, sort_keys=True, indent=4, separators=(',', ': '))
